spring.application.name=my-blog-back-app
blog.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
blog.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BlogDb;encrypt=true;trustServerCertificate=true;
blog.datasource.username=
blog.datasource.password=