spring.application.name=my-blog-back-app

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BlogDb;encrypt=true;trustServerCertificate=true;
spring.datasource.username=
spring.datasource.password=

spring.sql.init.schema-locations=classpath:database/schema.sql
spring.sql.init.mode=always

server.port=8080
server.servlet.context-path=/